Repository falsy-oss/falsy-nft-marketplace, pull requests merged in 2023-04, with the labels that each got.

#9 chore: Update UI
  marketplace/.eslintignore
  marketplace/.eslintrc.cjs
  marketplace/.gitignore
  marketplace/.npmrc
  marketplace/.prettierignore
  marketplace/.prettierrc
  marketplace/README.md
  marketplace/app.vue
  marketplace/nuxt.config.ts
  marketplace/package.json
  marketplace/playwright.config.ts
  marketplace/pnpm-lock.yaml
  marketplace/postcss.config.js
  marketplace/public/favicon.ico
  marketplace/src/app.css
  marketplace/src/app.d.ts
  marketplace/src/app.html
  marketplace/src/index.test.ts
  marketplace/src/routes/+layout.svelte
  marketplace/src/routes/+page.svelte
  marketplace/static/favicon.png
  marketplace/svelte.config.js
  marketplace/tailwind.config.js
  marketplace/tests/test.ts
  marketplace/tsconfig.json
  marketplace/vite.config.ts
  marketplace/yarn.lock
Labels: enhancement

#10 feat: Dockerize auth service
  auth-service/.dockerignore
  auth-service/Dockerfile
  auth-service/package.json
  auth-service/yarn.lock
Labels: bug

#12 [DEPLOYMENT][AUTH-SERVICE] Init health check module
  auth-service/package.json
  auth-service/src/app.module.ts
  auth-service/src/health/health.module.ts
  auth-service/src/health/health/health.controller.spec.ts
  auth-service/src/health/health/health.controller.ts
  auth-service/yarn.lock
Labels: deployment

#14 [SEARCH-SERVICE] Init search service
  search-service/.gitignore
  search-service/build.gradle
  search-service/gradle/wrapper/gradle-wrapper.jar
  search-service/gradle/wrapper/gradle-wrapper.properties
  search-service/gradlew
  search-service/gradlew.bat
  search-service/settings.gradle
  search-service/src/main/kotlin/com/falsyoss/searchservice/SearchServiceApplication.kt
  search-service/src/main/resources/application.properties
  search-service/src/test/kotlin/com/falsyoss/searchservice/SearchServiceApplicationTests.kt
Labels: feature

#15 [SEARCH-SERVICE] Init search service
  .vscode/settings.json
  search-service/build.gradle
  search-service/build.gradle.kts
  search-service/gradlew
  search-service/settings.gradle
  search-service/settings.gradle.kts
  search-service/src/main/kotlin/com/falsyoss/searchservice/SearchServiceApplication.kt
  search-service/src/test/kotlin/com/falsyoss/searchservice/SearchServiceApplicationTests.kt
Labels: feature

#17 chore: Clean up
  marketplace/.eslintignore
  marketplace/.eslintrc.cjs
  marketplace/.gitignore
  marketplace/.npmrc
  marketplace/.prettierignore
  marketplace/.prettierrc
  marketplace/README.md
  marketplace/package.json
  marketplace/playwright.config.ts
  marketplace/pnpm-lock.yaml
  marketplace/postcss.config.js
  marketplace/src/app.css
  marketplace/src/app.d.ts
  marketplace/src/app.html
  marketplace/src/index.test.ts
  marketplace/src/routes/+layout.svelte
  marketplace/src/routes/+page.svelte
  marketplace/static/favicon.png
  marketplace/svelte.config.js
  marketplace/tailwind.config.js
  marketplace/tests/test.ts
  marketplace/tsconfig.json
  marketplace/vite.config.ts
Labels: invalid

#21 :fire: remove blockchain-scan-service
  blockchain-scan-service/.eslintrc.js
  blockchain-scan-service/.gitignore
  blockchain-scan-service/.prettierrc
  blockchain-scan-service/README.md
  blockchain-scan-service/nest-cli.json
  blockchain-scan-service/package-lock.json
  blockchain-scan-service/package.json
  blockchain-scan-service/src/app.controller.spec.ts
  blockchain-scan-service/src/app.controller.ts
  blockchain-scan-service/src/app.module.ts
  blockchain-scan-service/src/app.service.ts
  blockchain-scan-service/src/main.ts
  blockchain-scan-service/test/app.e2e-spec.ts
  blockchain-scan-service/test/jest-e2e.json
  blockchain-scan-service/tsconfig.build.json
  blockchain-scan-service/tsconfig.json
Labels: feature
